### ISSUE TITLE
[FEAT] support regex or start-with for checks

### ISSUE THREAD

**Issue by Borda** [tianhaoz95/check-group#1078]
**Is your feature request related to a problem? Please describe.**
Having an option on how to group parametrized checks would very simplify the logic

**Describe the solution you'd like**
HAve simplification of using reg expressions so for example, instead of
```yaml
    paths:
      - "dockers/**"
    checks:
      - "build-conda (3.8, 1.10)"
      - "build-conda (3.8, 1.9)"
      - "build-conda (3.9, 1.11)"
      - "build-conda (3.9, 1.12)"
      - "build-cuda (3.8, 1.9, 11.1.1)"
      - "build-cuda (3.9, 1.10, 11.3.1)"
      - "build-cuda (3.9, 1.11, 11.3.1)"
      - "build-cuda (3.9, 1.12, 11.3.1)"
      - "build-cuda (3.9, 1.9, 11.1.1)"
```
I would write only
```yaml
    paths:
      - "dockers/**"
    checks:
      - r"build-conda (*)"
      - r"build-cuda (*)"
```

**Describe alternatives you've considered**
Or use it as a start with, so it could be:
```yaml
    paths:
      - "dockers/**"
    checks:
      - r"build-conda"
      - r"build-cuda"
```

**Additional context**
readability is very important for larger projects...
