### ISSUE TITLE
[BUG] Bot doesn't post a status on PRs after configuration

### ISSUE THREAD

**Issue by Thatkookooguy** [tianhaoz95/check-group#333]
**Describe the bug**
The bot is installed on all the repos in my organization kibibit.
When submitting PRs to project kibibit/achievibit, no check-group status shows even though a configuration file is defined

I also tried to run this in my own docker to make sure it's a problem in the app and not the server being down but couldn't get that to work. so maybe some documentation is needed in that department :-)

**To Reproduce**

my usage:
- [achievibit check-group config](https://github.com/Kibibit/achievibit/blob/beta/.github/checkgroup.yml)
- [achievibit pull request example](https://github.com/Kibibit/achievibit/pull/350)

1. Create a repo with the configuration from above
2. open a pull request
3. Scroll down to status checks
4. See that check-group status check **does not appear**

**Expected behavior**
Well... I expect to see the check-group status :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/10427304/116736255-4f28f580-a9f8-11eb-8f09-96a03ecdd252.png)

**Additional context**
my config:
```yaml
subprojects:
  - id: Server
    paths:
      - "server/**"
    checks:
      - "Run linters Server"
      - "Build Production"
      - "Server Unit Tests"
      - "API Tests"
      - "codecov/project"
      - "codecov/project/unit-test-server"
      - "codecov/project/api-tests"
  - id: Client
    paths:
      - "clients/**"
    checks:
      - "Build Production"
      - "Client Unit Tests"
      - "codecov/project"
      - "codecov/project/unit-test-client"
  - id: Achievements
    paths:
      - "achievements/**"
    checks:
      - "Run linters Achievements"
      - "Build Production"
      - "codecov/project"
      - "codecov/project/unit-test-achievements"
```
