### ISSUE TITLE
[BUG] Misconfigured checkgroup.yml fails silently and open

### ISSUE THREAD

**Issue by paulijones** [tianhaoz95/check-group#593]
**Describe the bug**
When checkgroup.yml file has a group in it with no checks, it fails open

**To Reproduce**

1. setup check-group per the instructions
2. add checkgroup.yml as:
```yaml
subprojects:
  - id: documentation
    paths:
      - "docs/**"
  - id: inventory
    paths:
      - "Inventory/**"
    checks:
      - "test"
      - "Single Service Check"
  - id: mediaplan
    paths:
      - "MediaPlan/**"
    checks:
      - "test"
      - "Single Service Check"
```
3. Open a pr and see check-group pass with (0/0)

**Expected behavior**
I would expect either a check failing, or that checkgroup assumes that its a project with no checks.
I did this because i had projects that i knew 

**Screenshots**
![image](https://user-images.githubusercontent.com/30155889/134987925-154fc7e5-42ce-4f9a-8eee-f817263acf2e.png)

**Additional context**
This could certainly be working as expected, i just didn't see it documented anywhere. Also if it could give some sort of error for debugging that would be very helpful.
